version: "3.8"

services:

  mongo:
    image: mongo:7
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"

  config-server:
    build: ./config-server
    container_name: config-server
    ports:
      - "8888:8888"

  eureka-server:
    build: ./eureka-server
    container_name: eureka-server
    ports:
      - "8761:8761"
    depends_on:
      - config-server

  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    ports:
      - "9090:9090"
    depends_on:
      - eureka-server
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  auth-service:
    build: ./auth-service
    container_name: auth-service
    ports:
      - "8081:8081"
    depends_on:
      - mongo
      - eureka-server
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  consumer-service:
    build: ./consumer-service
    container_name: consumer-service
    ports:
      - "8082:8082"
    depends_on:
      - mongo
      - eureka-server
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  tariff-service:
    build: ./tariff-service
    container_name: tariff-service
    ports:
      - "8083:8083"
    depends_on:
      - mongo
      - eureka-server
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  meter-service:
    build: ./meter-service
    container_name: meter-service
    ports:
      - "8084:8084"
    depends_on:
      - mongo
      - eureka-server
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  billing-service:
    build: ./billing-service
    container_name: billing-service
    ports:
      - "8085:8085"
    depends_on:
      - mongo
      - eureka-server
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  payment-service:
    build: ./payment-service
    container_name: payment-service
    ports:
      - "8086:8086"
    depends_on:
      - mongo
      - eureka-server
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  notification-service:
    build: ./notification-service
    container_name: notification-service
    ports:
      - "8087:8087"
    depends_on:
      - mongo
      - rabbitmq
      - eureka-server
    environment:
      - SPRING_PROFILES_ACTIVE=docker

volumes:
  mongo_data:
