package com.utilitybilling.notificationservice.enums;

public enum NotificationType {
	PASSWORD_RESET, PASSWORD_CHANGED, CONNECTION_REQUEST_ADMIN, CONNECTION_APPROVED, CONNECTION_REJECTED,
	BILL_GENERATED, BILL_OVERDUE, PAYMENT_OTP, PAYMENT_SUCCESS, PAYMENT_FAILED, INVOICE_PDF
}
